### ISSUE TITLE
CI not building book properly

### ISSUE THREAD

**Issue by kysolvik** [pyOpenSci/dev_guide#16]
New content isn't getting published if you don't "make book" before pushing changes

**Comment by choldgraf** [comment]
I can try to debug this - I was planning to update the jupyter book version we use anyway

**Comment by choldgraf** [comment]
I *think* I fixed this in #21 - the problem was that we weren't actually deleting old versions of files in the master build, but now they should be deleted and properly updated...let's see if that fixes it

**Comment by kysolvik** [comment]
Hey @choldgraf, thanks for looking into this! Your PR seems like it should've fixed the problem, but still seems to not be updating. 

I'm just looking at the relative link that you fixed in the [review template](https://www.pyopensci.org/dev_guide/appendices/templates.html) in #14. It's still the relative link in the [_build dir of the master branch](https://github.com/pyOpenSci/dev_guide/blob/master/_build/appendices/templates.md) and in the [appendices dir in the gh-pages branch](https://github.com/pyOpenSci/dev_guide/blob/gh-pages/appendices/templates.html) (which is what the site is sourced from). It's been updated in all of the content directories, but that update hasn't made it into the _build dirs. Any ideas?

**Comment by kysolvik** [comment]
Hey @choldgraf, have you had the chance to revisit this? 

@lwasser and I were also talking about if there's anything we could streamline/simplify since we're not using the more advanced jupyter books features like the code blocks and outputs.

thanks for all your help!!!

**Comment by choldgraf** [comment]
hey @kysolvik - I've been away at a conference so haven't had a chance to look at this. I can try to spend a little bit of time this week. I don't think that the build isn't updating because we are using advanced features - the auto-deploy script just isn't set up properly I think...will try to figure it out

**Comment by kysolvik** [comment]
ok, thanks @choldgraf!

**Comment by choldgraf** [comment]
in #22 I just removed the `_build` folder as I think it might have been preventing new versions of files from being built

(in a newer version of jupyter-book, the behavior changed so that if files in `content/` are newer than files in `_build/` then the re-build automatically happens, but I suspect that we're running an older version of jupyter-book that required you to manually delete the files in `_build/` if you wanted to rebuild them.)

In this case, I've just deleted that whole folder, which means it'll be re-build every time (and the information is redundant from the `content/` folder, so no need to keep it in the repo IMO.

Let's check again to see if the update worked when the merge finishes building the site. What's a thing we can look for to decide if it worked or not?

**Comment by kysolvik** [comment]
Hey @choldgraf! I think it worked! Just looking at that relative link that you corrected to an absolute link (under packaging guidelines here: https://www.pyopensci.org/dev_guide/appendices/templates.html#review-template), it's been updated now. 

I'm going to add a couple more things to the packaging guide today or tomorrow. I'll check to be sure they update and let you know

**Comment by kysolvik** [comment]
Closing this issue... thanks again Chris!

**Comment by choldgraf** [comment]
wohoo!

**Comment by lwasser** [comment]
you guys are awesome. thank you both!
